version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "cosmosapien/team"
    assignees:
      - "cosmosapien/team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "typer"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rich"
        update-types: ["version-update:semver-major"]
      - dependency-name: "openai"
        update-types: ["version-update:semver-major"]
      - dependency-name: "anthropic"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "cosmosapien/team"
    assignees:
      - "cosmosapien/team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "cosmosapien/team"
    assignees:
      - "cosmosapien/team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Pre-commit hooks
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "cosmosapien/team"
    assignees:
      - "cosmosapien/team"
    commit-message:
      prefix: "pre-commit"
      include: "scope"
    labels:
      - "dependencies"
      - "pre-commit"
    target-branch: "develop" 